ccwebsite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views
# import notifications.urls

urlpatterns = [
    path('admin/', admin.site.urls, name="Admin"),
    path('', include('home.urls')),
    path('',include('quizapp.urls')),
    path('post/', include('post.urls')),
    path('profile/', include('user_profile.urls')),
    path('comments/', include('comments.urls')),
    path('notification/', include('notif.urls')),

    # Account URLS
    url(r'^password_reset/$', views.PasswordResetView.as_view(), name='password_reset'),
    url(r'^password_reset/done/$', views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.PasswordResetConfirmView.as_view(),
        name='password_reset_confirm'),
    url(r'^reset/done/$', views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),

    # Extra URLS
    path('ckeditor/', include('ckeditor_uploader.urls')),
    url(r'^oauth/', include('social_django.urls', namespace='social')),
    # url('^inbox/notifications/', include(notifications.urls, namespace='notifications')),



    # url(r'^accounts/', includes('allauth.urls')),
    # oauth/ url will be accessed by Social site link to take to their website.


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# urlpatterns += staticfiles_urlpatterns()

home/urls.py
from django.urls import path
from django.conf.urls import url
from home import views

urlpatterns = [

    # Active URL's - Intuitive name of paths
    path('', views.index, name="Index"),

    path('filter-post-by/<str:tag_filter>/', views.index, name="index_tag"),

    path('personalised/<str:username>/', views.index, name="personalised_index"),

    path('most-liked/<str:liked>/', views.index, name="index_most_liked"),

    path('older-first/<str:older>/', views.index, name="index_older_first"),

    path('most-liked/<str:liked>/personalised/<str:username>/', views.index, name="personalised_index_most_liked"),

    path('older-first/<str:older>/personalised/<str:username>/', views.index, name="personalised_index_older_first"),

    path(
        'filter-post-by/<str:tag_filter>/personalised/<str:username>/',
        views.index,
        name="personalised_index_with_filter"
    ),

    path('add-to-calendar/<int:pk>/', views.AddToCalendar, name="add-to-calendar"),
    # path('login/', views.login_view, name="Login"),

    path('login/', views.ajax_login_view, name="ajax_login"),
    path('signup/', views.ajax_signup_view, name="ajax_signup"),
    path('logout/', views.logout_view, name="Logout"),
    path('search/', views.search, name='search'),

    # Inactive URL's
    # path('login/', views.login_view, name="Login"),
    # path('signup/', views.signup_view, name="Signup"),
]

home/models.py
# from django.db import models
# from django.contrib.auth.models import User
from django.contrib.auth import get_user_model


class EmailBackend(object):
    """
        An Email Backend to authenticate(Log In) user with Email ID.
        Source: StackOverflow
    """
    def authenticate(self, request, username=None, password=None, **kwargs):
        User = get_user_model()
        try:
            username = username.lower()
            user = User.objects.get(email=username)
        except User.DoesNotExist:
            return None
        else:
            if getattr(user, 'is_active', False) and user.check_password(password):
                return user
        return None

    def get_user(self, user_id):

        User = get_user_model()
        try:
            return User.objects.get(pk=user_id)
        except User.DoesNotExist:
            return None

home/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


class UserSignupForm(UserCreationForm):

    # Intuitive variable names
    GROUP_CHOICES = [
        ('teacher', 'Teacher'),
        ('student', 'Student'),
    ]
    choice = forms.ChoiceField(choices=GROUP_CHOICES, widget=forms.RadioSelect, required=True)

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'choice', 'password1', 'password2',)

    # To check if Email provided is unique or not
    def clean_email(self):
        email = self.cleaned_data.get('email')

        # Changing to lower case for uniformity.
        email = email.lower()

        username = self.cleaned_data.get('username')
        if email and User.objects.filter(email=email).exclude(username=username).exists():
            raise forms.ValidationError(u'Email already registered.')
        return email

home/views.py
from django.shortcuts import render, HttpResponseRedirect, HttpResponse, reverse, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from post.views import page_maker
from django.http import JsonResponse
from json import dump, dumps
# from django.contrib.auth import get_user_model
# from django.contrib.contenttypes.models import ContentType

# Imports for email
from django.template.loader import render_to_string
from django.core import mail
from django.utils.html import strip_tags

# Importing models
from comments.models import Comment
from django.contrib.auth.models import Group
from post.models import Tags, Post
from user_profile.models import UserProfile
from django.contrib.auth.models import User

# Importing Forms
from home.forms import UserSignupForm
from post.forms import PostForm
from comments.forms import CommentForm


# def search(request):
#     context = {}
#     url_parameter = request.GET.get('key')
#     if url_parameter:
#         users = User.objects.filter(username__icontains=url_parameter)
#     else:
#         users = User.objects.all()
#
#     # result = "SS"
#     # response = {
#     #     'result': result,
#     #     'userQs': userQs,
#     # }
#     # return JsonResponse(response)
#     if request.is_ajax():
#         html = render_to_string(
#             template_name="home/users-results-partial.html",
#             context={"persons": users}
#         )
#
#         data_dict = {"html_from_view": html}
#
#         return JsonResponse(data=data_dict, safe=False)
#
#     return render(request, "In.html", context=context)

def search(request):
    key = request.GET['key']
    if key:
        users = User.objects.filter(username__icontains=key)
        user_profiles = UserProfile.objects.filter(user__in=users)
    else:
        users = 'empty' # User.objects.all()
        user_profiles = UserProfile.objects.all()

    html = render_to_string(
        template_name="home/users-results-partial.html",
        context={
            'persons': users,
            'user_profiles': user_profiles,
        }
    )

    response = {
        'html': html
    }
    return JsonResponse(data=response, safe=False)

# def autocompleteModel(request):
#     if request.is_ajax():
#         q = request.GET.get('term', '').capitalize()
#         search_qs = Post.objects.filter(name__startswith=q)
#         results = []
#         print(q)
#         for r in search_qs:
#             results.append(r.FIELD)
#         data = dumps(results)
#     else:
#         data = 'fail'
#     mimetype = 'application/json'
#     return HttpResponse(data, mimetype)


def set_profile(request, user):
    """
        This function checks whether all necessary information about user is filled or not
        and sets profile.
        If profile is set successfully it returns True, otherwise False.
    """
    profile_qs = UserProfile.objects.filter(user=user)
    if profile_qs:
        profile = profile_qs.first()

        # Saving Group of user as Student by Default
        my_group = Group.objects.get(name='Student')
        my_group.user_set.add(request.user)
        my_group.save()

        if profile.is_password_set:
            if profile.is_email_verified:
                if len(str(user.email)) > 0:
                    if len(str(user.first_name)) > 0:
                        profile.is_profile_set = True
                        profile.save()
                        return True
                    else:
                        messages.info(request, f"Name is not set.")
                else:
                    messages.info(request, f"Email is not set.")
            else:
                messages.info(request, f"Email not verified")
        else:
            messages.info(request, f"Password is not set.")
        profile.is_profile_set = False
        profile.save()
        return False
    messages.error(request, f"User not found.")
    return False


def index(request, tag_filter=None, username=None, liked=None, older=None):
    """
        This function renders Home Page.
        If tag_filter = None, All posts are fetched
        otherwise posts from specific tags are fetched.
    """
    check_profile = None
    flag = False
    if request.user.is_authenticated:
        flag = set_profile(request, request.user)
        check_profile = UserProfile.objects.get(user=request.user)

    # User signup form, comment form, Post adding form
    form = UserSignupForm()
    comment_form = CommentForm()
    addpostform = PostForm()

    # Fetching posts as pages, all User Profiles, tags and comments
    posts = page_maker(request, Post, tag_filter=tag_filter, username=username, liked=liked, older=older)
    user_profiles = UserProfile.objects.all()
    tags = Tags.objects.all()
    comments = Comment.objects.all()  # Using overridden Model Manager all().

    # Context to be sent to template
    context = {
        'form': form,
        'addpostform': addpostform,
        'posts': posts,
        'tags': tags,
        'user_profiles': user_profiles,
        'comments': comments,
        'comment_form': comment_form,
    }
    if check_profile is not None:
        if not check_profile.is_profile_set:
            # messages.info(request, f"Set your profile first.")
            return HttpResponseRedirect(reverse('edit_profile', kwargs={'username': request.user.username}))

    if username is not None:
        messages.info(request, f"You are viewing Personalised Feed.")
    else:
        messages.info(request, f"You are viewing Public Feed.")

    return render(request, 'home/index.html', context)

    # Tried earlier:
    # if comment_form.is_valid():
    #     print(comment_form.cleaned_data)


# def personalised_index(request, username, tag_filter=None):
#     """
#         This function renders Personalised Home Page.
#         i.e. this page will contain post of only followed user.
#         If tag_filter = None, All posts are fetched
#         otherwise posts from specific tags are fetched.
#     """
#     check_profile = None
#     flag = False
#     user = User.objects.get(username=username)
#     if request.user == user:
#         if request.user.is_authenticated:
#             flag = set_profile(request, request.user)
#             check_profile = UserProfile.objects.get(user=request.user)
#
#         # User signup form, comment form, Post adding form
#         form = UserSignupForm()
#         comment_form = CommentForm()
#         addpostform = PostForm()
#
#         # Fetching posts as pages, all User Profiles, tags and comments
#         posts = page_maker(request, Post, tag_filter=tag_filter)
#         user_profiles = UserProfile.objects.all()
#         tags = Tags.objects.all()
#         comments = Comment.objects.all()  # Using overridden Model Manager all().
#
#         # Context to be sent to template
#         context = {
#             'form': form,
#             'addpostform': addpostform,
#             'posts': posts,
#             'tags': tags,
#             'user_profiles': user_profiles,
#             'comments': comments,
#             'comment_form': comment_form,
#         }
#         if check_profile is not None:
#             if not check_profile.is_profile_set:
#                 # messages.info(request, f"Set your profile first.")
#                 return HttpResponseRedirect(reverse('edit_profile', kwargs={'username': request.user.username}))
#
#         return render(request, 'home/post_display_personalised.html', context)
#     messages.info(request, f"You are unauthorized to view this page.")
#     return HttpResponseRedirect(reverse('Index'))


def ajax_login_view(request):
    """
        Function to login using AJAX.
    """
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        remember_me = request.POST.get('remember_me')
        user = authenticate(request, username=username, password=password)
        '''
            Response Codes(Acronyms):
            LS: Login success.
            LF: Login failed.
        '''       
        if user is not None:
            login(request, user)
            response = HttpResponse('LS')
            if remember_me is None:
                # Executed when remember_me is None i.e. not checked.
                if 'cook_user' and 'cook_pass' in request.COOKIES:
                    # Enters when either of the cookie is present.
                    # response = render(request,'blogapp/newhome.html',context)
                    response.delete_cookie('cook_user')
                    response.delete_cookie('cook_pass')
                    return response
                else:
                    # Enters when both of the cookie is not present i.e. deleted .
                    return response
            else:
                if 'cook_user' and 'cook_pass' not in request.COOKIES:
                    response.set_cookie('cook_user', username, max_age=86400, path='/')
                    response.set_cookie('cook_pass', password, max_age=86400, path='/')
                    return response
                else:
                    if username==request.COOKIES.get('cook_user') and password==request.COOKIES.get('cook_password'):                        
                        return response
                    elif username!=request.COOKIES.get('cook_user') or password!=request.COOKIES.get('password'):
                        response.set_cookie('cook_user', username, max_age=86400, path='/')
                        response.set_cookie('cook_pass', password, max_age=86400, path='/')
                        return response
        else:
            return HttpResponse('LF')
    # else:
    #     return redirect(HOME)


def logout_view(request):
    """
        A simple function to log out.
    """
    logout(request)

    # Success message
    messages.success(request, f"Logout Success")

    return HttpResponseRedirect(reverse('Index'))

home/templates/home/add_post.html
{% load materializecss %}
{# Adding post #}
{% if user.is_authenticated %}

{# Add Post enabled if User is authenticated  #}
    <form class="post_form" method="post" action="{% url 'ajax_add_post' %}" author="{{ user.username }}" data-success="{% url 'Index' %}">
        <ul class="collapsible white post-form-collapse" >
            <li>
                <div class="collapsible-header tooltipped dark2" data-tooltip="Click to Add Post.">
                    <strong>Add Post</strong>
                </div>
                <div class="collapsible-body">
                    {% csrf_token %}
                    {{ addpostform.media }}
                    {{ addpostform.title|materializecss:'col s6 m6, icon=title' }}
                    {{ addpostform.tags|materializecss:'col s6 m6, icon=bookmark' }}


                    {% if user.is_superuser %}
{#                     <div class="input-field col s12 m12 l12">#}
{#                        <ul id="">#}
{#                            <label>Signup as:</label>#}
{#                            <p>#}
{#                                <label for="scheduled">#}
{#                                    <input class="with-gap" type="checkbox" name="choice" value="" required id="scheduled"/>#}
{#                                    <span>Scheduled</span>#}
{#                                </label>#}
{#                            </p>#}
{#                        </ul>#}
{#                     </div>#}
                        {{ addpostform.is_scheduled|materializecss:'col s6 m6 l6' }}
                        {{ addpostform.draft|materializecss:'col s6 m6 l6' }}
                        <br><br><br><br><br><br><br>
                        {{ addpostform.post_content }}
                    {% endif %}
                    {{ addpostform.post_content }}
{#                    <span class="tooltipped" data-position="top" data-tooltip="Tick to save post as draft.">#}
                        {{ addpostform.draft|materializecss:'col s12 m12 l12' }}
{#                    </span>#}
{#                    {{ addpostform.post_on_date|materializecss:'col s8 m8, icon=account_circle' }}#}
                    <br><br><br>
                    <button class="btn waves-light" type="submit" name="action" value="post">Post
                        <i class="material-icons right">send</i>
                    </button>

{#                    <button class="btn waves-light" type="submit" name="action" value="draft">Save as Draft#}
{#                        <i class="material-icons right">drafts</i>#}
{#                    </button>#}

                </div>
            </li>
        </ul>
    </form>

{% else %}
{# Here user is NOT authenticated to a Login Modal will pop up asking user to log in First #}
    <ul class="collapsible">
        <li>
            <div class="collapsible-header tooltipped dark2" onclick="addToast('Login to add post!')" data-position="top" data-tooltip="Click to Add Post!">
                <a class="btn-flat modal-trigger dark2 col s12 m12 l12" href="#modal1" id="add-post-without-login" >
                    <strong>Add Post</strong>
                </a>
            </div>
        </li>
    </ul>
{% endif %}

{# Tried Earier: #}
{# CONTAINER #}
{#{% if user.is_authenticated %}#}
{#    <ul class="collection with-header" >#}
{#        <form method="post" action="{% url 'Add Post' %}">#}
{#        <li class="collection-header">#}
{#            <strong>Add Post</strong>#}
{#        </li>#}
{#        <li class="collection-item">#}
{#            {% csrf_token %}#}
{#            {{ addpostform.media }}#}
{#            {{ addpostform.title|materializecss:'col s6 m6, icon=account_circle' }}#}
{#            {{ addpostform.tags|materializecss:'col s6 m6, icon=account_circle' }}#}
{#            {{ addpostform.post_content }}#}
{#            <div>#}
{#                <button class="btn waves-light" type="submit" name="action">Post#}
{#                <i class="material-icons right">send</i>#}
{#            </button>#}
{#            </div>#}
{##}
{#        </li>#}
{#        </form>#}
{#    </ul>#}
{#{% else %}#}
{#    <ul class="collapsible">#}
{#        <li>#}
{#            <div class="collapsible-header" onclick="addPostToast()">#}
{#                <a class="btn-flat modal-trigger white black-text col s12 m12 l12" href="#modal1" id="add-post-without-login" >#}
{#                    <strong>Add Post</strong>#}
{#                </a>#}
{#            </div>#}
{#        </li>#}
{#    </ul>#}
{#{% endif %}#}

home/templates/home/index.html
{% extends 'base.html' %}
{% load materializecss %}
{% load static %}
{% comment %}
    Context Variables:
    form - Signup form
    user - Logged in User
    addpostform - Post Add Form
    posts - Posts
    tags - Tags
    user_profiles - Profiles of users
    comments - Comments
    comment_form - Comment Form
{% endcomment %}

{% block title %}
    Home
{% endblock %}

{% block content %}

    {# All content INSIDE id='parent' div #}
    <div id="parent">

        <div id="index-banner" class="parallax-container">
            <div class="section no-pad-bot">
                <div class="container">
                    <br><br><br><br>
                    <h1 class="header center white-text text-lighten-2">CC Club MNNIT</h1>
{#                    <h1 class="header center white-text text-lighten-2 hide-on-med-and-down" style="font-size: 6vw">CC Club MNNIT</h1>#}
{#                    <h1 class="header center white-text text-lighten-2 hide-on-large-only" style="font-size: 10vw">CC Club MNNIT</h1>#}
                    <div class="row center">
                        <h5 class="header col s12 light">A club for enthusiast coders at MNNIT Allahabad</h5>
                    </div>
                    <br><br>
                </div>
            </div>
            <div class="parallax"><img src="{% static 'b8.png' %}" alt="Un - splashed background img 1"></div>
        </div>
    </div>

    {% include 'home/navbar.html' %}

    <!-- Tab for Personalised and Public feed -->
    <ul class="row tabs tabs-fixed-width tab-demo">
        {% if user.username in request.build_absolute_uri and 'personalised/' in request.build_absolute_uri %}
        <li class="tab col s6 m6 l6 center" style="background: var(--background2)">
            <a class="tooltipped" data-tooltip="Personalised feed">
                <i class="material-icons small">personal_video</i>
            </a>
        </li>
        {% else %}
        <li class="tab col s12 m12 l12 center" style="background: var(--background2)">
            <a class="active tooltipped" data-tooltip="Public feed">
                <i class="material-icons small ">public</i>
            </a>
        </li>
        {% endif %}

    </ul>

    {# Tab for small screen to filter posts by tags #}
    <ul class="tabs tabs-fixed-width tab-demo hide-on-med-and-up">
        <li class="tab col center">
            <a target="_self" href="{% url 'Index' %}">Reset</a>
        </li>
    {% if user.username in request.build_absolute_uri and 'personalised/' in request.build_absolute_uri and user.is_authenticated %}
        {% for tag in tags %}
            {% if tag.name in request.build_absolute_uri %}
                <li class="tab col center amber"><a class="active" href="{% url 'personalised_index_with_filter' tag_filter=tag.name username=user.username %}" target="_self">{{ tag.name }}</a></li>
            {% else %}
                <li class="tab col center"><a class="" href="{% url 'personalised_index_with_filter' tag_filter=tag.name username=user.username %}" target="_self">{{ tag.name }}</a></li>
            {% endif %}
        {% endfor %}
    {% else %}
        {% for tag in tags %}
            {% if tag.name in request.build_absolute_uri %}
                <li class="tab col center amber"><a class="active" href="{% url 'index_tag' tag.name %}" target="_self">{{ tag.name }}</a></li>
            {% else %}
                <li class="tab col center"><a class="" href="{% url 'index_tag' tag.name %}" target="_self">{{ tag.name }}</a></li>
            {% endif %}
        {% endfor %}
    {% endif %}
    </ul>
    {# Small screen tab ended #}

    <div class="row">

        {# Left side Catergory Menu #}
        <div class="col m4 l3 hide-on-small-and-down">
            {% include 'home/left_side_bar.html' %}
        </div>

        {# Middle part #}
        <div class="col s12 m8 l6">
            {% if not user.is_superuser %}
                {% include 'home/add_post.html' %}
            {% endif %}
            <div class="post-display-home">
                <!-- Public feed -->
                {% include 'home/post_display.html' %}
            </div>
        </div>


        {# Right side Catergory Menu #}
        <div class="col l3 hide-on-med-and-down">
            {% include 'home/right_side_bar.html' %}
        </div>

    </div>

    {% include 'footer.html' %}
{% endblock %}









{#                     commenr #}
{#                    <li>#}
{#                        <ul class="collapsible collection-item">#}
{#                            <li>#}
{#                                <div class="collapsible-header"><i class="material-icons">mode_comment</i>Comments</div>#}
{#                                <div class="collapsible-body">#}
{#                                    <div>#}
{#                                       Username: *comment 1*#}
{#                                    </div>#}
{#                                    <div>#}
{#                                       Username: *comment 2*#}
{#                                    </div>#}
{#                                    <div class="divider"></div>#}
{#                                </div>#}
{#                            </li>#}
{#                        </ul>#}
{#                    </li>#}
{#                     comment ended #}

home/templates/home/modal_signup.html
{% load materializecss %}
    {# Signup Modal #}
    <div id="modal2" class="modal modal-fixed-footer">
        <form id="signup_form" class="col s12" method="post" action="{% url 'ajax_signup' %}" data-success="{% url 'Index' %}">
            <div class="modal-content">
                <h4>Signup Here</h4>

                <div class="row">
                {% csrf_token %}
                    {{ form.username|materializecss:'s12 m12, icon=account_circle' }}
                    <input type="hidden" id="id_username_hidden">
                    {{ form.first_name|materializecss:'s6 m6, icon=account_circle' }}
                    {{ form.last_name|materializecss:'s6 m6, icon=account_circle' }}
                    {{ form.email|materializecss:'s12 m12, icon=mail' }}

                    <!-- Choices -->
{#                     <div class="input-field col s12 m12  ">#}
{#                        <ul id="id_choice">#}
{#                            <i class="material-icons prefix">mail</i>#}
{#                            <label>Signup as:</label>#}
{#                            <p>#}
{#                                <label for="id_choice_0">#}
{#                                    <input class="with-gap st_choice" type="radio" name="choice" value="teacher" required id="id_choice_0" checked/>#}
{#                                    <span>Teacher</span>#}
{#                                </label>#}
{#                            </p>#}
{#                            <p>#}
{#                                <label for="id_choice_1">#}
{#                                    <input class="with-gap st_choice" type="radio" name="choice" value="student" required id="id_choice_1" />#}
{#                                    <span>Student</span>#}
{#                                </label>#}
{#                            </p>#}
{#                        </ul>#}
{#                     </div>#}
                    {{ form.password1|materializecss:'s12 m12, icon=account_circle' }}
                    <input type="hidden" id="id_password1_hidden">
                    {{ form.password2|materializecss:'s12 m12, icon=account_circle' }}
                    <input type="hidden" id="id_password2_hidden">
                </div>
            </div>
            <div class="modal-footer">
                <button class="btn waves-light" type="submit" name="action" onclick="submitfunsignup();">Signup
                        <i class="material-icons right">send</i>
                </button>
            </div>
        </form>
    </div>

home/templates/home/pagination.html
<!-- Code to make Pages from Posts -->
{% if posts.has_other_pages %}

    <ul class="pagination center-align">

        {# If there are posts before current post #}
        {% if posts.has_previous %}
            <li><a href="?page={{ posts.previous_page_number }}"><i class="material-icons">chevron_left</i></a></li>
        {% else %}
            <li class="disabled"><i class="material-icons">chevron_left</i></li>
        {% endif %}

        {% for i in posts.paginator.page_range %}

            {% if posts.number == i %}
                <li class="active teal"><a href="?page={{ i }}">{{ i }}</a></li>
            {% else %}
                <li><a href="?page={{ i }}">{{ i }}</a></li>
            {% endif %}

        {% endfor %}

        {# If there are posts after current post #}
        {% if posts.has_next %}
            <li><a href="?page={{ posts.next_page_number }}"><i class="material-icons">chevron_right</i></a></li>
        {% else %}
            <li class="disabled"><i class="material-icons">chevron_right</i></li>
        {% endif %}

    </ul>

{% endif %}

home/templates/home/signup_modal.html
{% load materializecss %}
    {# Signup Modal #}
    <div id="modal2" class="modal modal-fixed-footer">
        <form id="signup_form" class="col s12" method="post" action="{% url 'ajax_signup' %}" data-success="{% url 'Index' %}">
            <div class="modal-content">
                <h4>Signup Here</h4>

                <div class="row">
                {% csrf_token %}
                    {{ form.username|materializecss:'s12 m12, icon=account_circle' }}
                    <input type="hidden" id="id_username_hidden">
                    {{ form.first_name|materializecss:'s6 m6, icon=account_circle' }}
                    {{ form.last_name|materializecss:'s6 m6, icon=account_circle' }}
                    {{ form.email|materializecss:'s12 m12, icon=mail' }}

                    <!-- Choices -->
{#                     <div class="input-field col s12 m12  ">#}
{#                        <ul id="id_choice">#}
{#                            <i class="material-icons prefix">mail</i>#}
{#                            <label>Signup as:</label>#}
{#                            <p>#}
{#                                <label for="id_choice_0">#}
{#                                    <input class="with-gap st_choice" type="radio" name="choice" value="teacher" required id="id_choice_0" checked/>#}
{#                                    <span>Teacher</span>#}
{#                                </label>#}
{#                            </p>#}
{#                            <p>#}
{#                                <label for="id_choice_1">#}
{#                                    <input class="with-gap st_choice" type="radio" name="choice" value="student" required id="id_choice_1" />#}
{#                                    <span>Student</span>#}
{#                                </label>#}
{#                            </p>#}
{#                        </ul>#}
{#                     </div>#}
                    {{ form.password1|materializecss:'s12 m12, icon=account_circle' }}
                    <input type="hidden" id="id_password1_hidden">
                    {{ form.password2|materializecss:'s12 m12, icon=account_circle' }}
                    <input type="hidden" id="id_password2_hidden">
                </div>
            </div>
            <div class="modal-footer">
                <button class="btn waves-light" type="submit" name="action" onclick="submitfunsignup();">Signup
                        <i class="material-icons right">send</i>
                </button>
            </div>
        </form>
    </div>

home/templates/home/users-results-partial.html
{% comment %}
    Context Vars -
            'persons': users,
            'user_profiles': user_profiles,
{%  endcomment %}
{% if persons == 'empty' %}
    <p>Search to get result.</p>
{% elif persons %}
  <div>
  {% for person in persons %}
      <a class="chip" href="{% url 'User Profile' person.username %}">
          {% for user_profile in user_profiles %}
                {% if user_profile.user == person %}
                    <img src="{{ user_profile.avatar.url }}">
                {% endif %}
          {% endfor %}

          {{ person.username }}
      </a>
  {% endfor %}
  </div>
{% else %}
  <p>Search to get result.</p>
{% endif %}