ccwebsite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views
# import notifications.urls

urlpatterns = [
    path('admin/', admin.site.urls, name="Admin"),
    path('', include('home.urls')),
    path('',include('quizapp.urls')),
    path('post/', include('post.urls')),
    path('profile/', include('user_profile.urls')),
    path('comments/', include('comments.urls')),
    path('notification/', include('notif.urls')),

    # Account URLS
    url(r'^password_reset/$', views.PasswordResetView.as_view(), name='password_reset'),
    url(r'^password_reset/done/$', views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.PasswordResetConfirmView.as_view(),
        name='password_reset_confirm'),
    url(r'^reset/done/$', views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),

    # Extra URLS
    path('ckeditor/', include('ckeditor_uploader.urls')),
    url(r'^oauth/', include('social_django.urls', namespace='social')),
    # url('^inbox/notifications/', include(notifications.urls, namespace='notifications')),



    # url(r'^accounts/', includes('allauth.urls')),
    # oauth/ url will be accessed by Social site link to take to their website.


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# urlpatterns += staticfiles_urlpatterns()

home/urls.py
from django.urls import path
from django.conf.urls import url
from home import views

urlpatterns = [

    # Active URL's - Intuitive name of paths
    path('', views.index, name="Index"),

    path('filter-post-by/<str:tag_filter>/', views.index, name="index_tag"),

    path('personalised/<str:username>/', views.index, name="personalised_index"),

    path('most-liked/<str:liked>/', views.index, name="index_most_liked"),

    path('older-first/<str:older>/', views.index, name="index_older_first"),

    path('most-liked/<str:liked>/personalised/<str:username>/', views.index, name="personalised_index_most_liked"),

    path('older-first/<str:older>/personalised/<str:username>/', views.index, name="personalised_index_older_first"),

    path(
        'filter-post-by/<str:tag_filter>/personalised/<str:username>/',
        views.index,
        name="personalised_index_with_filter"
    ),

    path('add-to-calendar/<int:pk>/', views.AddToCalendar, name="add-to-calendar"),
    # path('login/', views.login_view, name="Login"),

    path('login/', views.ajax_login_view, name="ajax_login"),
    path('signup/', views.ajax_signup_view, name="ajax_signup"),
    path('logout/', views.logout_view, name="Logout"),
    path('search/', views.search, name='search'),

    # Inactive URL's
    # path('login/', views.login_view, name="Login"),
    # path('signup/', views.signup_view, name="Signup"),
]

quizapp/urls.py
from django.urls import path
from .import views as quizapp_views 
urlpatterns = [   
	path('<str:username>/quiz_home/',quizapp_views.quiz_home,name="quiz_home"), 
	path('<str:username>/quiz/<int:pk>/',quizapp_views.quiz_view,name="take_quiz"),
	path('<str:username>/quiz/<int:pk>/share/',quizapp_views.share_quiz_perfo,name="share_quiz_perfo"),
	path('quiz/submit_quiz/<int:pk>/',quizapp_views.submitquizview,name="submit_quiz"),
	path('create-quiz/',quizapp_views.create_quiz,name="create_quiz"),
	path('create-quiz/questions/',quizapp_views.create_questions,name="create_questions"),
	# path('take_quiz/',quizapp_views.take_quiz_view,name="take_quiz_vish"),
	path('create_quiz/questions/<int:pk>/',quizapp_views.ques_detail_view,name="ques_detail"),
]

quizapp/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
# Create your models here.


class Quiz(models.Model):
	title = models.CharField(max_length=100)
	no_of_ques = models.PositiveIntegerField(default=0)
	max_score = models.PositiveIntegerField(default=0)
	neg_marks = models.PositiveIntegerField(default=0)
	time_lim = models.PositiveIntegerField(help_text="Time Limit should be in MINUTES.")
	instructions = models.TextField()
	author  = models.ForeignKey(User,on_delete=models.DO_NOTHING)
	date_created = models.DateTimeField(default = timezone.now)
	def __str__(self):
		return "{}".format(self.title)
	class Meta:
		ordering = ['id']

class UserQuizResult(models.Model):
	user = models.ForeignKey(User,on_delete=models.CASCADE)
	quiz = models.ForeignKey(Quiz,on_delete=models.CASCADE)
	score = models.IntegerField(default=0)
	is_atm = models.BooleanField(default=0)


class Question(models.Model):
	quiz = models.ForeignKey(Quiz,on_delete=models.CASCADE)
	question = models.TextField()
	def __str__(self):
		return "{}".format(self.question)
	class Meta:
		ordering = ['id']


class CurrentQuiz(models.Model):
	user = models.ForeignKey(User,on_delete=models.CASCADE)
	quiz = models.ForeignKey(Quiz,on_delete=models.CASCADE)
	question = models.ForeignKey(Question,on_delete=models.CASCADE)
	sel_ans = models.CharField(max_length=1)
	is_atm = models.BooleanField(default=False)
	contrib = models.IntegerField(default=0)


class Option(models.Model):
	quiz = models.ForeignKey(Quiz,on_delete=models.CASCADE)
	question = models.ForeignKey(Question,on_delete=models.CASCADE)
	option1 = models.TextField()
	option2 = models.TextField()
	option3 = models.TextField(null=True,blank=True)
	option4 = models.TextField(null=True,blank=True)
	def __str__(self):
		return "{}{}{}{}".format(self.option1,self.option2,self.option3,self.option4)
	class Meta:
		ordering = ['id']


class Answer(models.Model):
	'''
		Here We have used a convention that if a question is True False Type then
		we will have option 1 set to True and option 2 set to False.
	'''
	quiz = models.ForeignKey(Quiz,on_delete=models.CASCADE)
	question = models.ForeignKey(Question,on_delete=models.CASCADE)

	Ans_Choices=(('1','option1'),('2','option2'),('3','option3'),('4','option4'))
	# def Ans_Choices(que):
		# here que is quizapp.Answer.question
		# return (('1',que.objects.all()),('2','option2'),('3','option3'),('4','option4'))
	# curr_question = Question.objects.get(id=id)
	# print(que)
	# def Ans_Choices():
		# obj = Option.objects.last()
	# 	curr_question = objs
	# 	# for obj in questions:
	# 	print(obj)
		# return(('1',getattr(obj,'option1')),('1',getattr(obj,'option2')),('1',getattr(obj,'option3')),('1',getattr(obj,'option4')))
		# return (('1','option1'),('2','option2'),('3','option3'),('4','option4'))
		# question = questions.filter(id = id)
		# for question in questions:
		# 	if(que == question.question):
			# return (('1',question.option1),('2',question.option2),('3',question.option3),('4',question.option4))
	corr_answer = models.CharField(max_length=1,choices=Ans_Choices)
	extra_info = models.TextField(null=True,blank=True)
	def __str__(self):
		return "{}".format(self.question)
	class Meta:
		ordering = ['id']


class RandomQuizQuestion(models.Model):
	user = models.ForeignKey(User,on_delete=models.CASCADE)
	quiz_ques_id = models.ForeignKey(Question,on_delete=models.CASCADE)

quizapp/views.py
from django.shortcuts import render,redirect,HttpResponse,HttpResponseRedirect,reverse
from django.contrib import messages
import random
from django.http import JsonResponse
from .models import UserQuizResult,CurrentQuiz,Quiz,Question,Option,Answer,RandomQuizQuestion
from django.contrib.auth.models import User 
from .forms import QuizCreationForm,QuestionCreationForm,OptionCreationForm,AnswerCreationForm
from django.contrib.auth.decorators import login_required,user_passes_test
'''
check funtion for user_passes_test decorator:-
'''
def is_admin(user):#this function return True only if user is an admin 
	if user:
		# if user.groups.filter(name="Teacher").count():
		# 	return True
		if user.is_superuser:
			return True
		else:
			return False
	else:
		return False
def is_atmt(request,question_id):
	for entry in CurrentQuiz.objects.all().filter(user=request.user,question_id=int(question_id)):
		if entry.is_atm == True:
			return entry.id
	return False

def is_corrt(question_id,sel_ans):
	print(int(question_id))
	print(Answer.objects.all().filter(question_id=int(question_id)).first().id)
	print(type(Answer.objects.all().filter(question_id=int(question_id)).first().id))
	print(type(question_id))
	if int(question_id)==Answer.objects.all().filter(question_id=int(question_id)).first().id:
		return sel_ans==Answer.objects.all().filter(question_id=question_id).first().corr_answer
	# for answer_ in Answer.objects.all():
	# 	answers_.append(answer_.question)
	# print(answers_)
	# for entry in answers_:
	# 	print(entry)
	# 	print(entry.question)
	# 	return sel_ans==entry.corr_answer
	# print(correct_answer)
	# if str(correct_answer) == question:
	# 	print("Ting")
	# print(correct_answer)
	# print(type(str(correct_answer)))
	# print(type(question))
	# return correct_answer==sel_ans 
# Create your views here.
@login_required
def quiz_home(request,username):
	quizes = Quiz.objects.all()
	return render(request,'quizapp/quiz_portal_home.html',{'quizes':quizes})
@login_required
def share_quiz_perfo(request,username,pk):
	quiz_atmpt = UserQuizResult.objects.all().filter(user=request.user,quiz_id=pk).first()
	# print(quiz_atmpt.user)
	if quiz_atmpt:
		context = {
			'title' : quiz_atmpt.quiz,
			'score' : quiz_atmpt.score,
			'max_score' : quiz_atmpt.quiz.max_score
		}
		return render(request,"quizapp/share_quiz_perfo.html",context)
	else:
		return HttpResponse("Please Attempt this quiz fisrt then you will be Automatically Redirected to this page!")


@login_required
def quiz_view(request,username,pk):
	if request.method=="GET" and request.GET.get('question_id') and request.GET.get('quiz'): # to handle Reset Button in each question
		question_id = request.GET.get('question_id')
		quiz = request.GET.get('quiz')
		# print(request.GET)
		question_=Question.objects.all().filter(id=question_id).first()#Question Object
		if is_atmt(request,question_id): # as is_atmt returns the id of the row(entry) of the attempt in CurrentQuiz Table
			# print("Attempted One")
			entry_id = is_atmt(request,question_id)
			CurrentQuiz.objects.get(id=entry_id).delete()
			data = {
					'SS':"Choice Reset Done!"
			}
			response = JsonResponse(data)
			return response


	if request.method=='POST': # To handle Submit Button in each question
		question_id = request.POST['question_id']
		sel_ans = request.POST['sel_ans']
		quiz = request.POST['quiz']
		# print(request.POST)
		question=Question.objects.all().filter(id=question_id).first().question
		quiz_ = Quiz.objects.all().filter(title=quiz).first() #Quiz Object
		question_=Question.objects.all().filter(id=question_id).first()#Question Object
		contrib = 0
		if is_atmt(request,question_id):
			# print("Attempted One")
			entry_id = is_atmt(request,question_id)
			if is_corrt(question_id,sel_ans):
				contrib = (quiz_.max_score)/(quiz_.no_of_ques)
			else:
				contrib = 0 - neg_marks
			entry = CurrentQuiz.objects.get(id=entry_id)
			entry.sel_ans = sel_ans
			entry.contrib=contrib
			entry.save()
		else:
			#Definitely Add new row
			# check is_atm for that question
			# print("None Attempted One") 
			if is_corrt(question_id,sel_ans):
				# print("Hello")
				contrib = (quiz_.max_score)/(quiz_.no_of_ques)
			else:
				# print("World")
				contrib = 0 - quiz_.neg_marks
			print(contrib)
			entry = CurrentQuiz.objects.create(
						user = request.user,
						contrib = contrib,
						quiz = quiz_,
						question = question_,
						sel_ans = sel_ans,
						is_atm = True,
					)
			entry.save()	
		data={ 'SS' :"Successfully Submitted."}
		'''SS:'''
		return JsonResponse(data)

	else:
		quiz = Quiz.objects.all().filter(id=pk).first()
		rows = UserQuizResult.objects.all().filter(quiz=quiz)
		for row in rows:
			if request.user==row.user:
				# messages.info(request, f"Sorry, You have Alredy Attempted this Quiz.");
				# return HttpResponseRedirect(reverse('quiz_home', kwargs={'username': request.user.username}));
				return HttpResponse("Sorry, You have Alredy Attempted this Quiz.")
		questions = Question.objects.all().filter(quiz=quiz) #return Query Set i.e. <QuerySet [<Question: Question object (1)>, <Question: Question object (2)>]>
		quiz_ques = RandomQuizQuestion.objects.all().filter(user=request.user).first()
		if not quiz_ques:
			questions_ = []
			for question_ in questions:
				questions_.append(question_)
			random.shuffle(questions_)
			for q in questions_: 
				RandomQuizQuestion.objects.create(
					user = request.user,
					quiz_ques_id  = q
				)
		random_questions = RandomQuizQuestion.objects.all().filter(user=request.user)
		options = Option.objects.all().filter(quiz=quiz) 
		# options_ = []
		# for que in random_questions:
		# 	for option_ in options:
		# 		if option_.question == que.quiz_ques_id:
		# 			options_.append(option_)
					# print(option_.question)
		# print(answers)
		# for random_question in random_questions:
			# print(random_question.quiz_ques_id)
		return render(request,'quizapp/take_quiz.html',{'quiz':quiz,'questions':random_questions,'options':options})
		'''
		Finally random_questions have are rows in which quiz_ques_id is a question and these questions are random. 
		options_ have option_ where option_.question are in sync with random questions
		'''


		'''
		Try of Random using Sessions.
		'''
		# if request.session.get('quiz_running') in request.session:
		# 	return render(request,'quizapp/take_quiz.html',{'quiz':quiz,'questions':request.session['quiz_running'],'options':options})
		# else:
		# 	questions_ = []
		# 	for question_ in questions:
		# 		questions_.append(question_)
		# 	random.shuffle(questions_)
		# 	# print(questions)
		# 	options = Option.objects.all().filter(quiz=quiz) 
			# answers = Answer.objects.all().filter(quiz=quiz)
			# for question in questions:
				# print(question.option1)
			# print(answers)
			# request.session['quiz_running'] = questions_
			# return render(request,'quizapp/take_quiz.html',{'quiz':quiz,'questions':request.session['quiz_running'],'options':options})


@login_required
def submitquizview(request,pk):
	# user,quiz,score created permanently for current user
	if request.method=="GET":
		# print(request.GET)
		user = request.user
		quiz = Quiz.objects.all().filter(id=pk).first()
		attempts = CurrentQuiz.objects.all().filter(user=user)
		summation = 0
		for attempt in attempts:
			summation += attempt.contrib
		entry = UserQuizResult.objects.create(
					user = user,
					quiz = quiz,
					score = summation,
					is_atm = True
				)
		entry.save()
		CurrentQuiz.objects.all().filter(user=request.user).delete()
		RandomQuizQuestion.objects.all().filter(user=request.user).delete()
		share_url = "/" + str(user.username) + "/quiz/" + str(pk) + "/share/"
		# profle_url = "/profile/" + str(request.user) + "/"
		# print(profle_url)
		data={ 'SS' :"Successfully Submitted the quiz.",
			   'hit': share_url }
		response = JsonResponse(data)
		# path = "/quiz/" + str(quiz.id)
		# print(path)
		# print(response.set_cookie('minutes',1, max_age=10*86400, path=path))
		# response.set_cookie('seconds',1, max_age=10*86400, path=path)
		# print("Cookie Set")
		return response
		# return HttpResponse("Your scored " + entry.score + " out of " + quiz.max_score)
	else:
		return HttpResponse("Badass Url!")

@login_required
@user_passes_test(is_admin,login_url="Index") #i.e. when is_admin is Fasle then goes to Index
def create_quiz(request):
	if request.method == 'POST':
		form = QuizCreationForm(request.POST)
		form.instance.instructions = request.POST.get('instr') #i.e. get('name_attribute')
		form.instance.author = request.user
		'''
		Above statement will throw following error:
			Cannot assign "'Ankit@mnnit.com'": "Quiz.author" must be a "User" instance.
		when
		'''
		if form.is_valid():
			form.save()
			# messages.success(request,f'Commeted Successfully!')
		# redirect(request.path_info)
			return redirect("create_questions")
		else:
			if form.errors:
				for field in form:
					for error in field.errors:
						print(error)
			return HttpResponse("Something Bad Just Happend")
	else:
		form = QuizCreationForm()
		context = {
			'form':form
		}
		return render(request,"quizapp/create_quiz.html",context)


@login_required
@user_passes_test(is_admin,login_url="Index") #i.e. when is_admin is Fasle then goes to Index
def create_questions(request):
	if request.method == 'POST':
		# print(request.POST)
		quiz = Quiz.objects.all().last()
		que_obj = Question.objects.create(
			quiz = quiz,
			question = request.POST['question']
		)
		opt_obj = Option.objects.create(
			quiz = quiz,
			question = Question.objects.all().last(),
			option1 = request.POST['option1'],
			option2 = request.POST['option2'],
			option3 = request.POST['option3'],
			option4 = request.POST['option4']
		)
		ans_obj = Answer.objects.create(
			quiz = quiz,
			question = Question.objects.all().last(),
			corr_answer = request.POST.get('corr_answer',False),#to handle multivalue dictionary error
			extra_info = request.POST['extra_info']	
		)

quizapp/templates/quizapp/create_questions.html
{% extends 'base.html' %}
{% load static %}
{%load quizapp_tags%}
{% block content%}
<div class="row">
<div class="col s4 m3">
  <ul id="ques_list" class="sidenav sidenav-fixed dark2">
    <li>
    	<div class="user-view">	
      		<a href="#user"><img class="circle" src="{{ user.userprofile.avatar.url }}"></a>
      		<a href="#user"><span>Hello, {{user.first_name}}</span></a>
    	</div>
    </li>
    	<li>
    		<table>
    			<tr>
    				<th>
    					Title
    				</th>
    				<td>
    					{{quiz.title}}
    				</td>
    			</tr>
    			<tr>
    				<th>
    					Max Ques.
    				</th>
    				<td>
    					{{quiz.no_of_ques}}
    				</td>
    			</tr>
    			<tr>
    				<th>
    					Time Limit
    				</th>
    				<td>
    					{{quiz.time_lim}}
    				</td>
    			</tr>
    		</table>
    	</li>
    {%if questions %}
    	{% for question in questions %}
			<li class="ques_list_item" >
				<a id="{{question.id}}" href="{%url 'ques_detail' question.id %}" style="text-overflow:ellipsis;overflow:hidden;white-space:nowrap;">{{forloop.counter}}. {{question}}</a>
			</li>
		{%endfor%}
	{%else%}
		<li>
			<a>No Questions till now.</a>
		</li>
	{%endif%}
  </ul>
</div>
{% if que_cnt < quiz.no_of_ques %}
<div class="container col s8 grey darken-2">
<form id="ques_form" method="post" action="">
	{%csrf_token%}
{{form_que}}
{{form_opt}}
	<div class="input-field col s12">
    <select id="id_corr_answer">
    	<option value="" disabled>Choose Correct Answer</option>
    	<option value="1">Option1</option>
    	<option value="2">Option2</option>
    	<option value="3">Option3</option>
    	<option value="4">Option4</option>
      <!-- <option value="" disabled>Choose Correct Answer</option>
      {% for x,y in form_ans.fields.corr_answer.choices %}
      {% if forloop.counter != 1 %}
      	<option value="{{x}}">{{y}}</option>
      {%endif%}
      {%endfor%} -->
    </select>
  </div>
{{form_ans.extra_info}}
   <button class="btn" type="submit" name="action">Submit Question
    	<i class="material-icons right">send</i>
  	 </button>
 </form>
</div>
{%else%}
<div class="container col s8 white-text center" style="padding-top: 20vh;">
    <h3>Hope You created a good Quiz!</h3>
</div>
{% endif %}
</div>



{%endblock%}

quizapp/templates/quizapp/create_quiz.html
{%extends 'base.html' %}
{%load static%}
{%load quizapp_tags%}
{%block content%}
<div class="container">
<div class="row">
    <form class="col s12" action="" method="post">
    	{% csrf_token %}
      <div class="row">
  		<div class="input-field col s12 grey darken-2">
          {{form.title}}
          <label for="title" class="white-text">Quiz-Title</label>
        </div>
      </div>
      <div class="row">
        <div class="input-field col s5 grey darken-2">
         {{form.no_of_ques}}
          <label for="no_of_ques" class="white-text">No. Of Questions</label>
        </div>
        <div class="input-field col s5 right grey darken-2">
          {{form.time_lim}}
          <label for="tim_lim" class="white-text">Time Limit</label>
        </div>
      </div>
      <div class="row">
        <div class="input-field col s5 grey darken-2">
         {{form.neg_marks}}
          <label for="no_of_ques" class="white-text">Negative Marks per Question</label>
        </div>
        <div class="input-field col s5 right grey darken-2">
          {{form.max_score}}
          <label for="tim_lim" class="white-text">Maximum Score</label>
        </div>
      </div>
      <div class="row">
        <div class="input-field col s12">
          <textarea id="instructions" name ="instr" class="materialize-textarea grey darken-2"></textarea>
          <label for="instructions" class="white-text">Instructions</label>
        </div>
      </div>
      <button class="btn waves-effect waves-light white-text" type="submit" name="action">Submit
    	<i class="material-icons right">send</i>
  	  </button>
    </form>
</div>
</div>
    {% include 'footer.html' %}
{% endblock %}

quizapp/templates/quizapp/pagination.html
<!--Pagination-->
        <nav class="d-flex justify-content-center wow fadeIn">
          <ul class="pagination pg-blue">

            <!--Arrow left-->
            <li class="page-item disabled">
              <a class="page-link" href="#" aria-label="Previous">
                <span aria-hidden="true">&laquo;</span>
                <span class="sr-only">Previous</span>
              </a>
            </li>

            <li class="page-item active">
              <a class="page-link" href="#">1
                <span class="sr-only">(current)</span>
              </a>
            </li>
            <li class="page-item">
              <a class="page-link" href="#">2</a>
            </li>
            <li class="page-item">
              <a class="page-link" href="#">3</a>
            </li>
            <li class="page-item">
              <a class="page-link" href="#">4</a>
            </li>
            <li class="page-item">
              <a class="page-link" href="#">5</a>
            </li>

            <li class="page-item">
              <a class="page-link" href="#" aria-label="Next">
                <span aria-hidden="true">&raquo;</span>
                <span class="sr-only">Next</span>
              </a>
            </li>
          </ul>
        </nav>